"""UniHack 2026 AI Product Intelligence application package."""

from .attribute_extraction import (
    AttributeEvidence,
    AttributeExtractionError,
    AttributeExtractionResult,
    ExtractedAttribute,
    RejectedAttribute,
    extract_attribute_values,
)
from .cross_source_validation import (
    ConflictInfo,
    CrossSourceValidationError,
    CrossSourceValidationResult,
    SourceAttributeValue,
    ValidatedAttribute,
    normalize_for_comparison,
    validate_cross_source,
)
from .confidence_scoring import (
    ConfidenceAssessment,
    ConfidenceScoringResult,
    calculate_confidence,
)
from .pipeline import (
    ProductIntelligencePipelineError,
    ProductIntelligenceResult,
    SourceSummary,
    run_pipeline,
)
from .diagnostics import Diagnostic
from .mpn_normalization import normalize_mpn
from .gemini_client import GeminiTransientError, TRANSIENT_RETRY_DELAYS_SECONDS
from .unit_normalization import (
    NormalizedMeasurement,
    measurements_equivalent,
    normalize_measurement,
)
from .catalog_input import (
    CatalogInputError,
    CatalogInputRow,
    brand_candidate,
    is_placeholder_brand,
    load_catalog_rows,
    select_catalog_row,
)
from .delivery_schema import (
    DeliverySchema,
    DeliverySchemaError,
    EXPECTED_DELIVERY_COLUMN_COUNT,
    load_delivery_rows,
    load_delivery_schema,
    select_delivery_row,
)
from .delivery_output import (
    DeliveryComparison,
    DeliveryFieldEvidence,
    DeliveryFieldDifference,
    compare_delivery_rows,
    map_raw_fields_to_delivery,
    map_verified_source_content_to_delivery,
)
from .reference_data import (
    AttributeReference,
    AttributeRule,
    BrandReference,
    CatalogReferenceResolution,
    ManufacturerReference,
    ReferenceResolutionResult,
    TaxonomyPath,
    TaxonomyReference,
    UOMReference,
    normalize_reference_value,
    resolve_catalog_row_references,
)
from .manufacturer_enrichment import (
    DEFAULT_APPROVED_DOMAINS,
    ManufacturerEnrichmentProvider,
    ManufacturerSource,
    RetrievedPayload,
    RetrievalResult,
)
from .source_history import VerifiedSourceHistory, VerifiedSourceRecord
from .verified_source_content import (
    SourceLink,
    StructuredProductData,
    VerifiedSourceContent,
    extract_verified_source_content,
)
from .catalogue_enrichment import (
    AttributeDeliveryMapping,
    AttributeDeliveryMappings,
    CatalogueEnrichmentError,
    CatalogueEnrichmentResult,
    EnrichmentSourceDiagnostic,
    EvaluationComparison,
    EvaluationFieldDifference,
    MappingDiagnostic,
    enrich_catalogue_row,
)
from .controlled_attribute_mapping import (
    ControlledAttributeMapping,
    ControlledAttributeMappingRegistry,
    resolve_controlled_attribute_mapping,
)
from .attribute_mapping_coverage import task42_candidate_mappings
from .review import (
    ReviewIssue,
    ReviewReport,
    build_review_report,
)
from .catalogue_batch import (
    BatchEvaluationDiagnostic,
    BatchResult,
    BatchReviewIssue,
    run_catalogue_batch,
)
from .source_discovery import (
    DiscoveredSourceCandidate,
    DiscoveredSourceVerificationResult,
    DiscoveryPilotRowResult,
    BraveSearchProvider,
    InMemorySourceSearchProvider,
    ManufacturerSourcePolicy,
    SearchResult,
    SearchProviderError,
    SearchTransportResponse,
    SerperSearchProvider,
    SourceDiscoveryResult,
    SourceSearchProvider,
    SourceVerificationDiagnostic,
    discover_and_verify_sources,
    discover_manufacturer_sources,
    generate_discovery_queries,
    run_discovery_pilot,
)
from .pilot_policies import (
    ControlledSourcePolicy,
    get_controlled_source_policy,
    get_pilot_source_policy,
    resolve_source_policy,
    resolve_source_policy_for_row,
)
from .runtime_policy import (
    IdentityResolutionResult,
    RuntimeDomainCandidate,
    RuntimeAuthorityEvidence,
    resolve_identity_and_source_policy,
)

__all__ = [
    "AttributeEvidence",
    "AttributeExtractionError",
    "AttributeExtractionResult",
    "ExtractedAttribute",
    "RejectedAttribute",
    "extract_attribute_values",
    "ConflictInfo",
    "CrossSourceValidationError",
    "CrossSourceValidationResult",
    "SourceAttributeValue",
    "ValidatedAttribute",
    "normalize_for_comparison",
    "validate_cross_source",
    "ConfidenceAssessment",
    "ConfidenceScoringResult",
    "calculate_confidence",
    "ProductIntelligencePipelineError",
    "ProductIntelligenceResult",
    "SourceSummary",
    "run_pipeline",
    "Diagnostic",
    "normalize_mpn",
    "GeminiTransientError",
    "TRANSIENT_RETRY_DELAYS_SECONDS",
    "NormalizedMeasurement",
    "measurements_equivalent",
    "normalize_measurement",
    "CatalogInputError",
    "CatalogInputRow",
    "brand_candidate",
    "is_placeholder_brand",
    "load_catalog_rows",
    "select_catalog_row",
    "DeliverySchema",
    "DeliverySchemaError",
    "EXPECTED_DELIVERY_COLUMN_COUNT",
    "load_delivery_rows",
    "load_delivery_schema",
    "select_delivery_row",
    "DeliveryComparison",
    "DeliveryFieldEvidence",
    "DeliveryFieldDifference",
    "compare_delivery_rows",
    "map_raw_fields_to_delivery",
    "map_verified_source_content_to_delivery",
    "AttributeReference",
    "AttributeRule",
    "BrandReference",
    "CatalogReferenceResolution",
    "ManufacturerReference",
    "ReferenceResolutionResult",
    "TaxonomyPath",
    "TaxonomyReference",
    "UOMReference",
    "normalize_reference_value",
    "resolve_catalog_row_references",
    "DEFAULT_APPROVED_DOMAINS",
    "ManufacturerEnrichmentProvider",
    "ManufacturerSource",
    "RetrievedPayload",
    "RetrievalResult",
    "VerifiedSourceHistory",
    "VerifiedSourceRecord",
    "SourceLink",
    "StructuredProductData",
    "VerifiedSourceContent",
    "extract_verified_source_content",
    "AttributeDeliveryMapping",
    "AttributeDeliveryMappings",
    "CatalogueEnrichmentError",
    "CatalogueEnrichmentResult",
    "EnrichmentSourceDiagnostic",
    "EvaluationComparison",
    "EvaluationFieldDifference",
    "MappingDiagnostic",
    "enrich_catalogue_row",
    "ControlledAttributeMapping",
    "ControlledAttributeMappingRegistry",
    "resolve_controlled_attribute_mapping",
    "task42_candidate_mappings",
    "ReviewIssue",
    "ReviewReport",
    "build_review_report",
    "BatchEvaluationDiagnostic",
    "BatchResult",
    "BatchReviewIssue",
    "run_catalogue_batch",
    "DiscoveredSourceCandidate",
    "DiscoveredSourceVerificationResult",
    "DiscoveryPilotRowResult",
    "BraveSearchProvider",
    "InMemorySourceSearchProvider",
    "SerperSearchProvider",
    "ManufacturerSourcePolicy",
    "SearchResult",
    "SearchProviderError",
    "SearchTransportResponse",
    "SourceDiscoveryResult",
    "SourceSearchProvider",
    "SourceVerificationDiagnostic",
    "discover_and_verify_sources",
    "discover_manufacturer_sources",
    "generate_discovery_queries",
    "run_discovery_pilot",
    "get_pilot_source_policy",
    "ControlledSourcePolicy",
    "get_controlled_source_policy",
    "resolve_source_policy",
    "resolve_source_policy_for_row",
    "IdentityResolutionResult",
    "RuntimeDomainCandidate",
    "RuntimeAuthorityEvidence",
    "resolve_identity_and_source_policy",
]
